### ISSUE TITLE
PHP Deprecation notice

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [inpsyde/backwpup#101] opened 2020-03-31 20:10 UTC
I am getting this error message in Query Monitor: 

> Non-static method BackWPup_Admin::admin_css() should not be called statically

![image](https://user-images.githubusercontent.com/13736892/78070554-9f7af180-73b9-11ea-9c8c-405a11e12660.png)

**Comment by Dinamiko** [comment] 2020-04-01 08:14
Hi @vijayaraghavanramanan,

can you please provide the steps to reproduce the issue and the versions of WordPress, PHP and BackWPup? thanks.

**Comment by vijayaraghavanramanan** [comment] 2020-04-02 16:39
PHP version 7.1.13

Wordpress version 5.4

Steps to reproduce: Install the plugin "Query Monitor" which by default has a menu item on top on activation. Then visit the front page, the menu turns orange, indicating a message. Click on that which opens the QM tool in bottom and see the message.

**Comment by kraftner** [comment] 2020-10-28 11:33
This still seems to be an issue:
- PHP 7.4.11
- WP 5.5.1
- BackWPup 3.8.0

The issue is here:

https://github.com/inpsyde/backwpup/blob/bdb72dd8d51076d7e11bf9ce52e0f94e1246ca33/inc/class-adminbar.php#L21

BackWPup 3.8.0 has this in the Changelog

https://github.com/inpsyde/backwpup/blob/bdb72dd8d51076d7e11bf9ce52e0f94e1246ca33/changelog.txt#L14

but due to the whole release being in one commit I couldn't see if this was an incomplete fix or somehow just missed with the message in the Changelog being wrong.

**Comment by cuongdcdev** [comment] 2020-12-01 16:40
this will be fixed in the next plugin update, for now, if you want, please download the patched plugin version  here: https://www.dropbox.com/s/8jd8hv226wrqobl/backwpup-fix-warning.zip?dl=0

**Closed by cuongdcdev** 2020-12-01 16:40 UTC
