### ISSUE TITLE
running a job white screens

### ISSUE THREAD

**Issue by chuckreynolds** [inpsyde/backwpup#12] opened 2014-04-24 18:47 UTC
Every time I run a job, it white screens and I get a log like the one below. The job screen remains white and will not be viewable until I remove the `backup-xxxx-xxxxxxx` directories. After doing this I can view the jobs page again, but if I run a job it white screens again.  

There are no Nginx errors in the log and access has the requests being successfully completed.

Please let me know if you need any more information to debug this issue.

Example Log

```
[INFO] BackWPup version 3.1.2; A project of Inpsyde GmbH
[INFO] WordPress version 3.9
[INFO] Blog url: http://example.com/
[INFO] BackWPup job: main-dropbox-backup; DBCHECK+DBDUMP+FILE+WPEXP+WPPLUGIN
[INFO] BackWPup no automatic job start configured
[INFO] BackWPup job started manually
[INFO] PHP ver.: 5.5.99-hiphop; srv; Linux
[INFO] Maximum PHP script execution time is 0 seconds
[INFO] MySQL ver.: 5.5.37-0ubuntu0.12.04.1
[INFO] curl ver.: 7.22.0; OpenSSL/1.0.1
[INFO] Temp folder is: /var/www/public/wp-content/uploaded/backwpup-xxxxxx-temp/
[INFO] Logfile is: /var/www/public/wp-content/uploaded/backwpup-xxxxxx-logs/backwpup_log_cdf88a_2014-04-24_11-31-21.html
[INFO] Backup type is: archive
[INFO] Backup file is: /var/www/public/wp-content/uploaded/backwpup-xxxxxx-temp/backwpup_cdf88a_20140424_113121.tar.gz
```

**Comment by widoz** [comment] 2019-01-28 16:16
@chuckreynolds Please try with the latest version 3.6.7, see if it works.

**Comment by chuckreynolds** [comment] 2019-01-28 20:46
FIVE YEARS AGO. lol. I haven't even used this plugin since. Can't test it but from what I remember it was an issue so bad that I stopped using it. so... Hope you guys get it fixed and deployed for everybody. Cheers

**Comment by widoz** [comment] 2019-01-29 08:41
Hi @chuckreynolds I know, but thank you for the reply. 

I'm not able to reproduce the issue and I haven't found any one else have experiencing the same.
I'm going to close this for now but for fill free to reopen in case you want to give a second chance to BackWPup. 

Thank you.

**Closed by widoz** 2019-01-29 08:41 UTC
Labels: waiting for response
