### ISSUE TITLE
DEPRECATED: Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by freica** [inpsyde/backwpup#108] opened 2020-08-31 06:19 UTC
Hi,
last week I changed something on my wordpress installation (changed Theme  to twentynineteen, BackWpUp Update to 3.7.1, PHP-Update 7.2->7.4)
Since this changes at the end of the backup-log I get perhaps 50 Messages of 
"DEPRECATED: Invalid characters passed for attempted conversion, these have been ignored"

The backup finishes successful.
What could be the matter of this?

**Comment by cuongdcdev** [comment] 2020-09-09 12:59
@freica 
The problem is because of PHP 7.4 and we also have to maintain BackWPUp to works with lower versions of PHP like 5.5 or 5.6 too.
The issue will be fixed in the next plugin update, which released in the next 1 or 2 weeks, in the meantime, you can replace this file with the one in `backwpup/inc/class-option.php`
https://gist.github.com/cuongdcdev/fdbd09b33941c1b2e1e522fba64d0d22
it’s should work!
(btw, the warning **does not affect** your backup job, please no worry ^^ )

**Closed** 2020-09-18 09:41 UTC

**Comment by cuongdcdev** [comment] 2020-11-17 12:22
Closed, it was fixed in the latest BWU 3.8
